<a href="https://colab.research.google.com/github/LiquidPunk/resume-projects/blob/main/DataCleaning_Preprocessing_autodeal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df1 = pd.read_csv('/content/usedcars_autodeal_1.csv')
df2 = pd.read_csv('/content/usedcars_autodeal_2.csv')

In [ ]:
# The two dfs should have the same shape
print(df1.shape)
print(df2.shape)

(1259, 7)
(1259, 7)

In [ ]:
# Filling the N/A from df1 with df2, and assigning it to df
df = df1.fillna(df2)

df.head(-10)

,Car Title,Car Price,Car Mileage,Car Transmission,Car Fuel Type,Seller Name,Seller Location
0,2023 Peugeot 2008 1.2 THP Allure A/T,"P1,285,500","3,257 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR"
1,2021 Peugeot 3008 1.6 THP Active A/T,"P1,131,500","10,821 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR"
2,2021 Peugeot 3008 1.6 THP Active A/T,"P1,195,500","9,240 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR"
3,2021 Peugeot 3008 1.6 THP Active A/T,"P1,285,500","9,457 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR"
4,2022 Peugeot Traveller 2.0 HDI ALL LG A/T,"P2,045,000","17,308 Km",Automatic,Diesel,BA Motors Philippines,"Makati City, Metro Manila, NCR"
...,...,...,...,...,...,...,...
1244,2020 Toyota Vios AT,"P700,000","22,351 Km",Automatic,Gasoline,BJA Car Hub,"Pasig City, Metro Manila, NCR"
1245,2019 Mitsubishi Xpander GLS AT,"P870,000","46,000 Km",Automatic,Gasoline,JZ Cars,"Quezon City, Metro Manila, NCR"
1246,2018 Toyota Fortuner G 2.4L AT Diesel,"P1,288,000","38,000 Km",Automatic,Diesel,JZ Cars,"Quezon City, Metro Manila, NCR"
1247,2018 Honda CR-V i-DTEC AT,"P1,220,000","65,000 Km",Automatic,Diesel,JZ Cars,"Quezon City, Metro Manila, NCR"
1248,2020 Honda HR-V AT,"P900,000","25,000 Km",Automatic,Gasoline,NaN,"Angeles City, Pampanga, Central Luzon"

In [ ]:
# Let's see how many N/As there are in the new df
df.isna().sum()

Car Title            0
Car Price            0
Car Mileage          0
Car Transmission     0
Car Fuel Type        0
Seller Name         91
Seller Location      0
dtype: int64

In [ ]:
df.shape

(1259, 7)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(1089, 7)

In [ ]:
# Removing the Year from Car Title and creating a new column for Year
df[['Year', 'Car Title']] = df['Car Title'].str.split(n=1, expand=True)

df.head(10)

,Car Title,Car Price,Car Mileage,Car Transmission,Car Fuel Type,Seller Name,Seller Location,Year
0,Peugeot 2008 1.2 THP Allure A/T,"P1,285,500","3,257 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2023
1,Peugeot 3008 1.6 THP Active A/T,"P1,131,500","10,821 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021
2,Peugeot 3008 1.6 THP Active A/T,"P1,195,500","9,240 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021
3,Peugeot 3008 1.6 THP Active A/T,"P1,285,500","9,457 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021
4,Peugeot Traveller 2.0 HDI ALL LG A/T,"P2,045,000","17,308 Km",Automatic,Diesel,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022
5,Peugeot 2008 1.2 THP Allure A/T,"P1,285,500","7,214 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022
6,Peugeot 2008 1.2 THP Allure A/T,"P1,285,500","6,856 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022
7,Hyundai Tucson GL 2.0L AT Gasoline,"P788,000","40,000 Km",Automatic,Gasoline,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017
8,Hyundai Tucson 2.0 GLS AT,"P898,000","27,000 Km",Automatic,Diesel,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017
9,Toyota Vios 1.3E MT,"P538,000","45,000 Km",Manual,Gasoline,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017

In [ ]:
# Creating column containing the cars brand
df['Car Brand'] = df['Car Title'].apply(lambda x: x.split(' ', 1)[0].strip())

df.head(10)

,Car Title,Car Price,Car Mileage,Car Transmission,Car Fuel Type,Seller Name,Seller Location,Year,Car Brand
0,Peugeot 2008 1.2 THP Allure A/T,"P1,285,500","3,257 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2023,Peugeot
1,Peugeot 3008 1.6 THP Active A/T,"P1,131,500","10,821 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot
2,Peugeot 3008 1.6 THP Active A/T,"P1,195,500","9,240 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot
3,Peugeot 3008 1.6 THP Active A/T,"P1,285,500","9,457 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot
4,Peugeot Traveller 2.0 HDI ALL LG A/T,"P2,045,000","17,308 Km",Automatic,Diesel,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022,Peugeot
5,Peugeot 2008 1.2 THP Allure A/T,"P1,285,500","7,214 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022,Peugeot
6,Peugeot 2008 1.2 THP Allure A/T,"P1,285,500","6,856 Km",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022,Peugeot
7,Hyundai Tucson GL 2.0L AT Gasoline,"P788,000","40,000 Km",Automatic,Gasoline,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017,Hyundai
8,Hyundai Tucson 2.0 GLS AT,"P898,000","27,000 Km",Automatic,Diesel,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017,Hyundai
9,Toyota Vios 1.3E MT,"P538,000","45,000 Km",Manual,Gasoline,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017,Toyota

In [ ]:
df['Car Mileage'] = df['Car Mileage'].str.rstrip(' Km')
df['Car Price'] = df['Car Price'].str.lstrip('P')

df.head()

,Car Title,Car Price,Car Mileage,Car Transmission,Car Fuel Type,Seller Name,Seller Location,Year,Car Brand
0,Peugeot 2008 1.2 THP Allure A/T,"1,285,500","3,257",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2023,Peugeot
1,Peugeot 3008 1.6 THP Active A/T,"1,131,500","10,821",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot
2,Peugeot 3008 1.6 THP Active A/T,"1,195,500","9,240",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot
3,Peugeot 3008 1.6 THP Active A/T,"1,285,500","9,457",Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot
4,Peugeot Traveller 2.0 HDI ALL LG A/T,"2,045,000","17,308",Automatic,Diesel,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022,Peugeot

In [ ]:
df['Car Mileage'] = df['Car Mileage'].str.replace(',', '', regex=True).astype('Int64')
df['Car Price'] = df['Car Price'].str.replace(',', '', regex=True).astype('Int64')

In [ ]:
df.head(10)

,Car Title,Car Price,Car Mileage,Car Transmission,Car Fuel Type,Seller Name,Seller Location,Year,Car Brand
0,Peugeot 2008 1.2 THP Allure A/T,1285500,3257,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2023,Peugeot
1,Peugeot 3008 1.6 THP Active A/T,1131500,10821,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot
2,Peugeot 3008 1.6 THP Active A/T,1195500,9240,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot
3,Peugeot 3008 1.6 THP Active A/T,1285500,9457,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot
4,Peugeot Traveller 2.0 HDI ALL LG A/T,2045000,17308,Automatic,Diesel,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022,Peugeot
5,Peugeot 2008 1.2 THP Allure A/T,1285500,7214,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022,Peugeot
6,Peugeot 2008 1.2 THP Allure A/T,1285500,6856,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022,Peugeot
7,Hyundai Tucson GL 2.0L AT Gasoline,788000,40000,Automatic,Gasoline,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017,Hyundai
8,Hyundai Tucson 2.0 GLS AT,898000,27000,Automatic,Diesel,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017,Hyundai
9,Toyota Vios 1.3E MT,538000,45000,Manual,Gasoline,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017,Toyota

In [ ]:
pd.set_option('display.max_rows', 10)

name_column = df['Car Title']
print(name_column)
print("\n")

0             Peugeot 2008 1.2 THP Allure A/T
1             Peugeot 3008 1.6 THP Active A/T
2             Peugeot 3008 1.6 THP Active A/T
3             Peugeot 3008 1.6 THP Active A/T
4        Peugeot Traveller 2.0 HDI ALL LG A/T
                        ...
1237    Isuzu Traviz 2.5L Utility Van Dual AC
1238              Ford EcoSport Trend 1.5L MT
1239                    Toyota Hilux G 4X2 AT
1240       Toyota FJ Cruiser 4.0L AT Gasoline
1241                     Honda BR-V 1.5 S CVT
Name: Car Title, Length: 1089, dtype: object

In [ ]:
# Extract alphanumeric and space characters from the 'Car Title' column to create the 'Car Name' column.
df['Car Name'] = df['Car Title'].str.extract('([a-zA-Z0-9 -]+)')

# Display the first 10 rows of the DataFrame.
df.head(10)

,Car Title,Car Price,Car Mileage,Car Transmission,Car Fuel Type,Seller Name,Seller Location,Year,Car Brand,Car Name
0,Peugeot 2008 1.2 THP Allure A/T,1285500,3257,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2023,Peugeot,Peugeot 2008 1
1,Peugeot 3008 1.6 THP Active A/T,1131500,10821,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot,Peugeot 3008 1
2,Peugeot 3008 1.6 THP Active A/T,1195500,9240,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot,Peugeot 3008 1
3,Peugeot 3008 1.6 THP Active A/T,1285500,9457,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2021,Peugeot,Peugeot 3008 1
4,Peugeot Traveller 2.0 HDI ALL LG A/T,2045000,17308,Automatic,Diesel,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022,Peugeot,Peugeot Traveller 2
5,Peugeot 2008 1.2 THP Allure A/T,1285500,7214,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022,Peugeot,Peugeot 2008 1
6,Peugeot 2008 1.2 THP Allure A/T,1285500,6856,Automatic,Gasoline,BA Motors Philippines,"Makati City, Metro Manila, NCR",2022,Peugeot,Peugeot 2008 1
7,Hyundai Tucson GL 2.0L AT Gasoline,788000,40000,Automatic,Gasoline,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017,Hyundai,Hyundai Tucson GL 2
8,Hyundai Tucson 2.0 GLS AT,898000,27000,Automatic,Diesel,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017,Hyundai,Hyundai Tucson 2
9,Toyota Vios 1.3E MT,538000,45000,Manual,Gasoline,AutoDeal SELECT,"Makati City, Metro Manila, NCR",2017,Toyota,Toyota Vios 1

In [ ]:
# # Remove 'AT', 'MT', or 'CVT' from car Name
# df['Car Name'] = df['Car Name'].str.replace(r'\s(AT|A/T|MT|M/T|CVT)', '', regex=True)

In [ ]:
# Extract the first two words from the 'Car Name' column and join them to create a new column.
df['Car Name'] = df['Car Name'].str.split(n=2).str[:2].str.join(' ')

In [ ]:
name_column = df['Car Name']
print(name_column)
print("\n")

0            Peugeot 2008
1            Peugeot 3008
2            Peugeot 3008
3            Peugeot 3008
4       Peugeot Traveller
              ...
1237         Isuzu Traviz
1238        Ford EcoSport
1239         Toyota Hilux
1240            Toyota FJ
1241           Honda BR-V
Name: Car Name, Length: 1089, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1089 entries, 0 to 1241
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Car Title         1089 non-null   object
 1   Car Price         1089 non-null   Int64
 2   Car Mileage       1089 non-null   Int64
 3   Car Transmission  1089 non-null   object
 4   Car Fuel Type     1089 non-null   object
 5   Seller Name       1015 non-null   object
 6   Seller Location   1089 non-null   object
 7   Year              1089 non-null   object
 8   Car Brand         1089 non-null   object
 9   Car Name          1089 non-null   object
dtypes: Int64(2), object(8)
memory usage: 95.7+ KB

In [ ]:
df.columns

Index(['Car Title', 'Car Price', 'Car Mileage', 'Car Transmission',
       'Car Fuel Type', 'Seller Name', 'Seller Location', 'Year', 'Car Brand',
       'Car Name'],
      dtype='object')

In [ ]:
df.to_csv('AutoDeal_Used_Cars.csv', index=False)